In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
from tensorflow.keras import backend as K
import numpy as np

def grad( y, x ):
    return Lambda( lambda z: K.gradients( z[ 0 ], z[ 1 ] ), output_shape = [1] )( [ y, x ] )

def network( i ):
    a = Lambda(lambda x: K.log( x + 2 ) )( i )
    return a

fixed_input = Input(shape=(1,))
# double = Input(tensor=tf.Variable( [ 2.0 ] ) )
unit_activation = tf.keras.initializers.Ones()
dense_dummy_layer = keras.layers.Dense(units=1,use_bias=False,
                                      kernel_initializer=unit_activation)(fixed_input)
# a = network(fixed_input)
a = network(dense_dummy_layer)

b = grad( a, fixed_input )
c = grad( b, fixed_input )
# d = grad( c, fixed_input )
# e = grad( d, fixed_input )


In [2]:
x = np.array([[1],
            [2],
            [3]])
model = Model( inputs = [ fixed_input], outputs = [ a,b] )



In [3]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 1)]          0                                            
__________________________________________________________________________________________________
dense (Dense)                   (None, 1)            1           input_1[0][0]                    
__________________________________________________________________________________________________
lambda (Lambda)                 (None, 1)            0           dense[0][0]                      
__________________________________________________________________________________________________
lambda_1 (Lambda)               [(None, 1)]          0           lambda[0][0]                     
                                                                 input_1[0][0]                

In [4]:
print( model.predict( x, steps = 1 ) )

[array([[1.0986123],
       [1.3862944],
       [1.609438 ]], dtype=float32), [array([[0.33333334],
       [0.25      ],
       [0.2       ]], dtype=float32)]]


In [5]:
for i in range(1,4):
    print(np.log(i+2),1/(i+2),-1/(i+2)**2)

1.0986122886681098 0.3333333333333333 -0.1111111111111111
1.3862943611198906 0.25 -0.0625
1.6094379124341003 0.2 -0.04


### Trying new things

In [6]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
from tensorflow.keras import backend as K
import numpy as np

def grad( y, x ):
    return Lambda( lambda z: K.gradients( z[ 0 ], z[ 1 ] ))( [ y, x
                                                             ] )

def network( i ):
    a = Lambda(lambda x: K.log( x + 2 ) )( i )
    return a

fixed_input = Input(shape=(2,))
# double = Input(tensor=tf.Variable( [ 2.0 ] ) )
unit_activation = tf.keras.initializers.Ones()
# dense_dummy_layer = keras.layers.Dense(units=2,use_bias=False,
#                                       kernel_initializer=unit_activation)(fixed_input)
# a = network(fixed_input)
# a = network(dense_dummy_layer)
a = Lambda(lambda x: x[:,0]*x[:,1]) (fixed_input)

# taking derrivative with respect to secon variable
b = keras.layers.Lambda(lambda z: K.gradients(z[0],z[1])) ([a,fixed_input])
# c = grad( b, fixed_input )
# d = grad( c, fixed_input )
# e = grad( d, fixed_input )


In [7]:
x = np.array([[1,4],
            [2,5],
            [3,6]])
model = Model( inputs = [ fixed_input], outputs = [a, b] )


In [8]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
lambda_3 (Lambda)               (None,)              0           input_2[0][0]                    
__________________________________________________________________________________________________
lambda_4 (Lambda)               [(None, 2)]          0           lambda_3[0][0]                   
                                                                 input_2[0][0]                    
Total params: 0
Trainable params: 0
Non-trainable params: 0
__________________________________________________________________________________________________


# model.summary()

In [9]:
print( model.predict( x, steps = 1 ) )

[array([ 4., 10., 18.], dtype=float32), [array([[4., 1.],
       [5., 2.],
       [6., 3.]], dtype=float32)]]


In [10]:
for i in range(1,4):
    print(np.log(i+2) + i,1/(i+2),-1/(i+2)**2)

2.09861228866811 0.3333333333333333 -0.1111111111111111
3.386294361119891 0.25 -0.0625
4.6094379124341005 0.2 -0.04


## Finding the Hessian

In [11]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
from tensorflow.keras import backend as K
import numpy as np

def hes( y, x ):
    return Lambda( lambda z: tf.hessians( z[ 0 ], z[ 1 ] ), output_shape = [1] )( [ y, x ] )

def network( i ):
    a = Lambda(lambda x: K.log( x + 2 ) )( i )
    return a

fixed_input = Input(shape=(1,))
# double = Input(tensor=tf.Variable( [ 2.0 ] ) )
unit_activation = tf.keras.initializers.Ones()
dense_dummy_layer = keras.layers.Dense(units=1,use_bias=False,
                                      kernel_initializer=unit_activation)(fixed_input)
# a = network(fixed_input)
a = network(dense_dummy_layer)

b = hes( a, fixed_input )
# c = grad( b, fixed_input )
# d = grad( c, fixed_input )
# e = grad( d, fixed_input )


In [12]:
x = np.array([[1],
            [2],
            [3]])
model = Model( inputs = [ fixed_input], outputs = [b] )



In [13]:
model.summary()

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, 1)]          0                                            
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 1)            1           input_3[0][0]                    
__________________________________________________________________________________________________
lambda_5 (Lambda)               (None, 1)            0           dense_1[0][0]                    
__________________________________________________________________________________________________
lambda_6 (Lambda)               [(None, 1, None, 1)] 0           lambda_5[0][0]                   
                                                                 input_3[0][0]              

In [14]:
print( model.predict( x, steps = 1 ) )

[array([[[[-0.11111112],
         [ 0.        ],
         [ 0.        ]]],


       [[[ 0.        ],
         [-0.0625    ],
         [ 0.        ]]],


       [[[ 0.        ],
         [ 0.        ],
         [-0.04      ]]]], dtype=float32)]


In [15]:
for i in range(1,4):
    print(np.log(i+2),1/(i+2),-1/(i+2)**2)

1.0986122886681098 0.3333333333333333 -0.1111111111111111
1.3862943611198906 0.25 -0.0625
1.6094379124341003 0.2 -0.04


## Putting everything inside a custom Model

In [16]:
class CustomModel(tf.keras.Model):

    def __init__(self):
        super(CustomModel, self).__init__()
        self.input_layer = Lambda(lambda x: K.log( x+2  ) )

    def findGrad(self,func,argm):
        return keras.layers.Lambda(lambda x: K.gradients(x[0],x[1])) ([func,argm])
    
    def call(self, inputs):
        Z = self.input_layer(inputs)
        Z_1 = self.findGrad(Z,inputs)
        #     return self.dense2(x)
        #     print("\n\n\n this is the answer:",self.square_layer(inputs))
        #     print("hre is a break")
        return Z_1


custom_model = CustomModel()

In [17]:
x = np.array([[0.],
            [1],
            [2]])

In [18]:
custom_model.predict(x)

[array([[0.5       ],
        [0.33333334],
        [0.25      ]], dtype=float32)]

## Poisson equation for $x^3$

Focus on the findPde layer, input_layer is justa dummy with log in it. IT doesnt matter

In [331]:
class CustomModel(tf.keras.Model):

    def __init__(self):
        super(CustomModel, self).__init__()
        self.input_layer = Lambda(lambda x: K.log( x+2  ) )

    def findGrad(self,func,argm):
        return keras.layers.Lambda(lambda x: K.gradients(x[0],x[1])[0]) ([func, argm])
    
    def findPde(self, func, argm):
        return keras.layers.Lambda(lambda z: z[0] + 6*z[1]) ([func, argm])
    
    def call(self, inputs):
        Z = self.input_layer(inputs)
        Z_1 = self.findGrad(Z,inputs)
        #     return self.dense2(x)
        #     print("\n\n\n this is the answer:",self.square_layer(inputs))
        #     print("hre is a break")
        return Z_1, self.findPde(Z_1, inputs)


custom_model = CustomModel()

In [332]:
x = np.array([[0.],
            [1],
            [2]])

In [333]:
x = np.random.uniform(0,3,100).reshape((100,1))

In [335]:
np.concatenate([custom_model.predict(x)[1],6*x+custom_model.predict(x)[0]],axis=1)

array([[ 2.20146704,  2.20146702],
       [ 1.71498108,  1.71498096],
       [ 5.88981819,  5.88981825],
       [ 1.10338783,  1.10338783],
       [ 9.36182308,  9.36182347],
       [ 9.07505512,  9.07505475],
       [ 8.39815235,  8.39815301],
       [17.51659203, 17.51659367],
       [13.56720161, 13.56720128],
       [ 9.55588818,  9.55588772],
       [ 6.03108692,  6.03108687],
       [17.01443291, 17.01443357],
       [14.88874817, 14.88874678],
       [ 4.36989927,  4.36989905],
       [ 0.83081353,  0.83081348],
       [11.28807449, 11.28807375],
       [ 8.95215893,  8.95215936],
       [13.18354416, 13.18354389],
       [ 6.21052885,  6.2105288 ],
       [18.07797813, 18.07797776],
       [14.68864918, 14.68865004],
       [ 3.98990107,  3.98990114],
       [17.82394409, 17.82394499],
       [12.99127388, 12.99127364],
       [17.73463631, 17.73463773],
       [ 8.8322897 ,  8.83228934],
       [11.3368721 , 11.33687302],
       [ 2.44668818,  2.44668795],
       [ 6.72441816,

In [326]:
x + custom_model.predict(x)[0]

array([[2.00117844],
       [1.52394515],
       [0.52260817],
       [2.33294922],
       [1.39929653],
       [1.91182102],
       [0.57568057],
       [3.17875688],
       [0.68931116],
       [0.9623731 ]])

## Gradient of multi-dimensional function

In [19]:
class CustomModel(tf.keras.Model):

    def __init__(self):
        super(CustomModel, self).__init__()
#         self.input_layer = Lambda(lambda x: K.log(x[:,0:1]+2) + x[:,1:2]**2 * x[:,2:3] + x[:,2:3]**3  )
#         self.input_layer = Lambda(lambda x: x[:,0:1] * x[:,1:2] * x[:,2:3]  )
        self.input_layer = Lambda(lambda x:x[0]*x[1])
#         self.grad_layer = Lambda(lambda x: K.gradients(x[0],x[1][:,0:1]))

    def findGrad(self,func,argm):
#         x_1 = self.input_copy[:,0:1]
# #         x_2 = argm[1]
# #         x_3 = argm[2]
#         print("x_1_type is ",type(x_1))
#         print(x_1)
        return keras.layers.Lambda(lambda x: tf.gradients(x[0],x[1][0])) ([func,argm])
#         return K.gradients(func,argm)
    
    def call(self, inputs):
        input_1,input_2 = inputs
        Z = self.input_layer([input_1,input_2])
        Z_1 = self.findGrad(Z,inputs)
        #     return self.dense2(x)
        #     print("\n\n\n this is the answer:",self.square_layer(inputs))
        #     print("hre is a break")
#         Z_2 = self.findGrad(Z_1,inputs)
        return  Z_1


custom_model = CustomModel()

In [20]:
x_1 = np.array([[0.],
            [1.],
            [2]])
x_2 = np.array([[3.],
            [4.],
            [5]])
# x = np.array([0.,1,2])
# x = x[:,np.newaxis]

In [21]:
custom_model.compile()

In [22]:
pred_val = custom_model.predict(x=[x_1,x_2])
pred_val

[array([[3.],
        [4.],
        [5.]], dtype=float32)]

## Laplacian of multi-dimensional function

In [294]:
class CustomModel(tf.keras.Model):

    def __init__(self):
        super(CustomModel, self).__init__()
#         self.input_layer = Lambda(lambda x: K.log(x[:,0:1]+2) + x[:,1:2]**2 * x[:,2:3] + x[:,2:3]**3  )
#         self.input_layer = Lambda(lambda x: x[:,0:1] * x[:,1:2] * x[:,2:3]  )
#         self.input_layer = Lambda(lambda x: tf.sin(x[0]) + tf.square(x[1])*x[2] + tf.exp(x[2]) )
        self.input_layer = Lambda(lambda x: tf.sin(x[:,0:1]) + tf.square(x[:,1:2])*x[:,2:3] + tf.exp(x[:,2:3]) )
#         self.grad_layer = Lambda(lambda x: K.gradients(x[0],x[1][:,0:1]))


    def findGrad(self,func,argm):
        try:
            return keras.layers.Lambda(lambda z: [tf.gradients(z[0],x_i,
                                                               unconnected_gradients='zero')
                                                  for x_i in z[1] ]) ([func,argm])
        except Exception as e:
            print("error occured in find gradient lambda layer of type {} as follows: ".format(type(e)),e)
            
            
    def findSecGrad(self,func,argm):
        try:
            # list containng diagonal entries of hessian matrix. Note that  tf.gradients 
            #returns a list of tensors and hence thats why we have  a [0] at the end of  
            #the tf.gradients fucntion as tf.gradients(func,argm) [0]
            del_sq_layer = keras.layers.Lambda( lambda z: [ tf.gradients(z[0][i], z[1][i],
                                                              unconnected_gradients='zero') [0]
                                                  for i in range(len(z[1])) ] ) ([func,argm])
            return sum(del_sq_layer)
                
        except Exception as e:
            print("Error occured in find laplacian lambda layer of type {} as follows: ".format(type(e)),e)
    
    
    def call(self, inputs):
        input_1,input_2,input_3 = inputs
#         Z = self.input_layer([input_1, input_2, input_3])
        inputs_conc = keras.layers.concatenate(inputs)
        Z = self.input_layer(inputs_conc)
        Z_1 = self.findGrad(Z,inputs)
        #     return self.dense2(x)
        #     print("\n\n\n this is the answer:",self.square_layer(inputs))
        #     print("hre is a break")
        Z_2 = self.findSecGrad(Z_1, inputs)
        return  Z_2


custom_model = CustomModel()

In [295]:
x_1 = np.array([[0.],
            [1.],
            [2],
             [4.]  ], dtype=np.float32)
x_2 = np.array([[3.],
            [4.],
            [5],
              [6.] ],dtype=np.float32)
x_3 = np.array([[9.],
            [10.],
            [16],
             [15]  ],dtype=np.float32)
# x = np.array([0.,1,2])
# x = x[:,np.newaxis]
X = np.concatenate([x_1,x_2,x_3], axis=1)

In [296]:
custom_model.compile()

In [297]:
pred_val = custom_model.predict(x=[X[:,0:1],X[:,1:2],X[:,2:3]])
pred_val

array([[8.1210840e+03],
       [2.2045623e+04],
       [8.8861420e+06],
       [3.2690482e+06]], dtype=float32)

In [298]:
-tf.sin(x_1)+ 2*x_3 + np.exp(x_3)

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[8.1210840e+03],
       [2.2045623e+04],
       [8.8861420e+06],
       [3.2690480e+06]], dtype=float32)>

## Note for finding  gradients

1. Can use lambda layers to find gradient with respect to different dimension of input like x,y,z,t.
2. If we feed the input as one single block of array(np,tf), then there is problem in using tf.gradients(function,input), since the returned gradient is some kind of sum of gradients in different dim. Please see the tf.gradients() manual.
3. A work around will be to feed the different attributes(features) of the data as different inputs so we can find the partial derrivative with respect to each input dim without a problem. Please see the section on graddient of multi-dim function.

### Regarding second gradient

1. Seems to be working fine except for some weird instances where None is returned and there is exception thrown while converting this None to a tensor.
2. Key point being using the notes above to find the gradient with respect to different input separately and then finally use another lambda layer to find partial derrivative of each of the partial derrivative.
3. Regarding the form of the del_sq layer in laplacian:   
    Note that  tf.gradients 
    returns a list of tensors and hence thats why we have  a [0] at the end of  
    the tf.gradients fucntion as tf.gradients(func,argm) [0]

## Next thing to do

Incorporate the lapace layer into the PINN with poission 2d problem.