# Random trials to understand functioning of Keras APIs

### Importing all the packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras

In [2]:
dummy_input = np.ones((10,3)) #batch_size =10, attribute size = 3
dummy_input_layer = keras.layers.Input(shape=(3,),name="first_input")
dummy_dense_layer = keras.layers.Dense(3,name="dummy_dense")(dummy_input_layer)
dummy_model = keras.Model(dummy_input_layer,dummy_dense_layer)

In [3]:
dummy_output = np.zeros((10,1))
dummy_model.compile(loss="mse")
history_dum_2 = dummy_model.fit(dummy_input,dummy_output,epochs=2)

Epoch 1/2
1/1 [==============================] - 0s 12ms/step - loss: 0.3099
Epoch 2/2
1/1 [==============================] - 0s 1ms/step - loss: 0.2962


In [4]:
dummy_model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
first_input (InputLayer)     [(None, 3)]               0         
_________________________________________________________________
dummy_dense (Dense)          (None, 3)                 12        
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________


In [6]:
np.random.seed(123)
act_layer = keras.layers.Activation("relu")
dummy_input = tf.constant(-1*np.ones((5,2,1)),dtype=float)
print(dummy_input)
# act_layer(dummy_input)

tf.Tensor(
[[[-1.]
  [-1.]]

 [[-1.]
  [-1.]]

 [[-1.]
  [-1.]]

 [[-1.]
  [-1.]]

 [[-1.]
  [-1.]]], shape=(5, 2, 1), dtype=float32)


In [18]:
np.random.seed(123)
lamba_layer = keras.layers.Lambda(tf.square)
dummy_input = tf.constant(np.arange(10),dtype=float)
lamba_layer(dummy_input)


<tf.Tensor: shape=(10,), dtype=float32, numpy=array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.], dtype=float32)>

In [76]:
from tensorflow.keras import backend as K
dummy_input = tf.constant(np.arange(5).reshape((5,1)),dtype=float)
input_layer = tf.keras.layers.Input(shape=(1,),name="main_input")
square_layer = keras.layers.Lambda(tf.square)(input_layer)

# model = keras.Model(inputs=[dummy_input], outputs=[gradient_layer])

In [84]:
class GradLayer(keras.layers.Layer):
    def __init__(self,**kwargs):
        super(GradLayer, self).__init__(**kwargs)
        self.org_input = tf.constant(np.arange(10),dtype=float)
    def call(self, inputs):
        return tf.gradients(inputs,self.org_input)


In [110]:
output_layer = GradLayer()

## Creating a custom model

In [116]:
class CustomModel(keras.Model):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.input_layer = tf.keras.layers.Input(shape=(1,),name="main_input")
#         self.square_layer = keras.layers.Lambda(tf.square)(input_layer)
    def call(self, inputs):
        Z = self.input_layer(inputs)
#         square = self.square_layer(Z)
        return Z

In [117]:
custom_model = CustomModel()
seq_model = keras.Sequential()

In [118]:
dummy_input = np.arange(5).reshape((5,1))
dummy_output = np.zeros((5,1))

In [242]:
class GradLayer(keras.layers.Layer):
    def __init__(self,**kwargs):
        super(GradLayer, self).__init__(**kwargs)
#         self.org_input = tf.constant(np.arange(10),dtype=float)
    def call(self, inputs,orig_input):
        return tf.keras.backend.gradients(inputs,orig_input)

In [345]:
class CustomModel(tf.keras.Model):

  def __init__(self):
    super(CustomModel, self).__init__()
    self.dense0 = keras.layers.Dense(10)
#     self.dense1 = tf.keras.layers.Dense(4, activation=tf.nn.relu)
#     self.dense2 = tf.keras.layers.Dense(5, activation=tf.nn.softmax)
    self.square_layer = keras.layers.Lambda(tf.square)
    self.dense1 = tf.keras.layers.Dense(1)
#     self.grad_layer = GradLayer()

  def call(self, inputs):
    Z = self.dense0(inputs)
    x = self.square_layer(Z)
#     return self.dense2(x)
#     print("\n\n\n this is the answer:",self.square_layer(inputs))
#     print("hre is a break")
    return self.dense1(x)
    

custom_model = CustomModel()

In [346]:
custom_model.compile()

In [347]:
custom_model.predict(dummy_input)

array([[ 0.        ],
       [-0.02545756],
       [-0.10183023],
       [-0.22911838],
       [-0.40732092]], dtype=float32)

In [250]:
custom_model.fit(dummy_input,dummy_output)

1/1 [==============================] - 0s 1ms/step - loss: 0.0000e+00


In [251]:
custom_model.predict(dummy_input)

array([[ 0],
       [ 1],
       [ 4],
       [ 9],
       [16]])

In [256]:
custom_model.summary()

Model: "custom_model_40"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lambda_76 (Lambda)           multiple                  0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
